# Generated by Django 2.1.2 on 2018-11-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reason',
            field=models.CharField(choices=[('SUGGEST TABOO WORDS', 'suggest taboo words'), ('FILE COMPLAINT', 'file complaint'), ('OTHER', 'other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.TextField(default='Type message here'),
        ),
    ]
