# Generated by Django 2.1.2 on 2018-11-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_system', '0002_auto_20181125_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reason',
            field=models.CharField(choices=[('OTHER', 'Other'), ('SUGGEST TABOO WORDS', 'Suggest Taboo Words'), ('FILE A COMPLAINT', 'File A Complaint')], default='other', max_length=20),
        ),
    ]
