# Generated by Django 2.1.2 on 2018-11-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg_system', '0004_auto_20181127_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_archive',
            field=models.BooleanField(default=True),
        ),
    ]
