# Generated by Django 2.1.2 on 2018-11-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg_system', '0005_auto_20181127_1835'),
        ('msg_system', '0005_auto_20181127_1712'),
    ]

    operations = [
    ]
