# Generated by Django 2.1.2 on 2018-12-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg_system', '0006_merge_20181127_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_archive',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_archive',
        ),
    ]
