# Generated by Django 2.1.2 on 2018-11-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181123_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cohort',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Guest User'), (1, 'Ordinary User'), (2, 'Super User')], default=0),
        ),
    ]
