# Generated by Django 2.1.2 on 2018-12-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doc_to_fix',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
