# Generated by Django 2.1.2 on 2018-12-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_doc_to_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doc_to_fix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
