# Generated by Django 2.1.2 on 2018-12-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181206_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doc_to_fix',
            field=models.IntegerField(null=True),
        ),
    ]
