# Generated by Django 2.1.2 on 2018-12-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181207_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_theme_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
