# Generated by Django 2.1.2 on 2018-12-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181206_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doc_to_fix',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
