# Generated by Django 2.1.2 on 2018-11-23 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('privacy', models.CharField(choices=[('PUB', 'Public'), ('R', 'Restricted'), ('S', 'Shared'), ('PRIV', 'Private')], max_length=4)),
                ('content', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=0)),
                ('lock_status', models.BooleanField(default=False)),
                ('locked_by', models.CharField(max_length=30)),
                ('edit_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('users_that_read', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('users_that_write', models.ManyToManyField(related_name='Contributors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('owner', 'title')},
        ),
    ]
