# Generated by Django 2.1.2 on 2018-11-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20181124_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='privacy',
            field=models.TextField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restricted'), ('SHARED', 'Shared'), ('PRIVATE', 'Private')], max_length=10),
        ),
    ]
