# Generated by Django 2.1.2 on 2018-11-25 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_auto_20181125_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pending_contributors',
            field=models.ManyToManyField(related_name='Invited', to=settings.AUTH_USER_MODEL),
        ),
    ]
