# Generated by Django 2.1.2 on 2018-11-28 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_pending_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='locked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locker', to=settings.AUTH_USER_MODEL),
        ),
    ]
