# Generated by Django 2.1.2 on 2018-11-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20181127_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='txt',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
