# Generated by Django 2.1.2 on 2018-12-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cmd_txt',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='cur_ver',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
