# Generated by Django 2.1.2 on 2018-12-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_last_edited_by'),
        ('documents', '0009_document_old_ver'),
    ]

    operations = [
    ]
