# Generated by Django 2.1.2 on 2018-12-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_merge_20181204_1531'),
        ('documents', '0010_merge_20181204_1447'),
    ]

    operations = [
    ]
