# Generated by Django 2.1.2 on 2018-12-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_merge_20181204_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='formatting_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
