# Generated by Django 2.1.2 on 2018-12-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_formatting_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='update_info',
            field=models.TextField(default=''),
        ),
    ]
